const yoKaiList = [
    { name: "Alcaldero", img: "alcaldero.png" },
    { name: "Sinná", img: "sinna.png" },
    { name: "Sinnareno", img: "sinnareno.png" },
    { name: "Katano", img: "katano.png" },
    { name: "Katananái", img: "katananai.png" },
    { name: "Katakroken", img: "katakroken.png" },
    { name: "Mochimacho", img: "mochimacho.png" },
    { name: "Machimío", img: "machimio.png" },
    { name: "Yelmandante", img: "yelmandante.png" },
    { name: "Juntollero", img: "juntollero.png" },
    { name: "Genedáver", img: "genedaver.png" },
    { name: "Flamileón", img: "flamileon.png" },
    { name: "Tembloleón", img: "tembloleon.png" },
    { name: "Sirleón", img: "sirleon.png" },
    { name: "Ludorái", img: "ludorai.png" },
    { name: "Lustre", img: "lustre.png" },
    { name: "Furtre", img: "Furtre.png" },
    { name: "Dortre", img: "dortre.png" },
    { name: "Benkei", img: "benkei.png" },
    { name: "B3-NK1", img: "b3-nk1.png" },
    { name: "Sushiyama", img: "sushiyama.png" },
    { name: "Kapunki", img: "kapunki.png" },
    { name: "Lucharabajo", img: "lucharabajo.png" },
    { name: "Camperabajo", img: "camperabajo.png" },
    { name: "Chafarabajo", img: "chafarabajo.png" },
    { name: "Osfurio", img: "osfurio.png" },
    { name: "Sacoco", img: "sacoco.png" },
    { name: "Mokopavo", img: "mokopavo.png" },
    { name: "Pachús", img: "pachus.png" },
    { name: "Komemo", img: "komemo.png" },
    { name: "Tontolín", img: "tontolin.png" },
    { name: "Yopaso", img: "yopaso.png" },
    { name: "Puf", img: "puf.png" },
    { name: "Yanomás", img: "yanomas.png" },
    { name: "Algazara", img: "algazara.png" },
    { name: "Labizula", img: "labizula.png" },
    { name: "Cotilleja", img: "cotilleja.png" },
    { name: "Marulleja", img: "marulleja.png" },
    { name: "Esquelleja", img: "esquelleja.png" },
    { name: "Cupístolo", img: "cupistolo.png" },
    { name: "Casanovo", img: "casanovo.png" },
    { name: "Casanono", img: "casanono.png" },
    { name: "Ondívoro", img: "ondivoro.png" },
    { name: "Coberturo", img: "coberturo.png" },
    { name: "Estatinarca", img: "estatinarca.png" },
    { name: "Telespejo", img: "telespejo.png" },
    { name: "Malpejismo", img: "malpejismo.png" },
    { name: "Ilúho", img: "iluho.png" },
    { name: "Elúho", img: "eluho.png" },
    { name: "Ubiúho", img: "ubiuho.png" },
    { name: "Trilépata", img: "trilepata.png" },
    { name: "Tetrariosa", img: "tetrariosa.png" },
    { name: "Tengu", img: "tengu.png" },
    { name: "Flamngu", img: "flamngu.png" },
    { name: "Kyubi", img: "kyubi.png" },
{ name: "Nievacolas", img: "nievacolas.png" },
{ name: "Tentelento", img: "tentelento.png" },
{ name: "Tentemacho", img: "tentemacho.png" },
{ name: "Tenterila", img: "tenterila.png" },
{ name: "Nihablar", img: "nihablar.png" },
{ name: "Impás", img: "impas.png" },
{ name: "Murallín", img: "murallin.png" },
{ name: "Lorigón", img: "lorigon.png" },
{ name: "Inquielifante", img: "inquielifante.png" },
{ name: "Perselefante", img: "perselefante.png" },
{ name: "Globqueo", img: "globqueo.png" },
{ name: "Globtundente", img: "globtundente.png" },
{ name: "Montaña Loca", img: "montaña_loca.png" },
{ name: "Lord Lava", img: "lord_lava.png" },
{ name: "Rebelcebú", img: "rebelcebu.png" },
{ name: "Caporrista", img: "caporrista.png" },
{ name: "Hermanión", img: "hermanion.png" },
{ name: "Pegarabajo", img: "pegarabajo.png" },
{ name: "Enormarabajo", img: "enormarabajo.png" },
{ name: "Cuernarabajo", img: "cuernarabajo.png" },
{ name: "Castelius III", img: "castelius_III.png" },
{ name: "Castelius II", img: "castelius_II.png" },
{ name: "Castelius I", img: "Castelius_I.png" },
{ name: "Maxicastelius", img: "Maxicastelius.png" },
{ name: "Robonyan", img: "robonyan.png" },
{ name: "Aureonyan", img: "aureonyan.png" },
{ name: "Pom", img: "pom.png" },
{ name: "Flus", img: "flus.png" },
    { name: "Deslumbrella", img: "deslumbrella.png" },
    { name: "Rechinella", img: "rechinella.png" },
    { name: "Esquelebella", img: "esquelebella.png" },
    { name: "Ningarra", img: "ningarra.png" },
    { name: "Habilgarra", img: "habilgarra.png" },
    { name: "Cantigarra", img: "cantigarra.png" },
    { name: "Escanlofrío", img: "escanlofrio.png" },
    { name: "Frihuahua", img: "frihuahua.png" },
    { name: "Lavadenco", img: "lavadenco.png" },
    { name: "Jibanyan", img: "jibanyan.png" },
    { name: "Espinyan", img: "espinyan.png" },
    { name: "Pelochnyan", img: "pelochnyan.png" },
    { name: "Kappandante", img: "kappandante.png" },
    { name: "Kappadachín", img: "kappadachin.png" },
    { name: "Kapparfista", img: "kapparfista.png" },
    { name: "Komasan", img: "komasan.png" },
    { name: "Komaleón", img: "komaleon.png" },
    { name: "Komajiro", img: "komajiro.png" },
    { name: "Komatigrado", img: "komatigrado.png" },
    { name: "Baku", img: "baku.png" },
    { name: "Blanpir", img: "blanpir.png" },
    { name: "Pufipatitas", img: "pufipatitas.png" },
    { name: "Pufilindo", img: "pufilindo.png" },
    { name: "Pufimaloso", img: "pufimaloso.png" },
    { name: "Fristina", img: "fristina.png" },
    { name: "Granizia", img: "granizia.png" },
    { name: "Dámona", img: "damona.png" },
{ name: "Cimbrón", img: "cimbron.png" },
{ name: "Pasodón", img: "pasodon.png" },
{ name: "Ritma", img: "ritma.png" },
{ name: "Kieroto", img: "kieroto.png" },
{ name: "Zampo", img: "zampo.png" },
{ name: "Abuzampa", img: "abuzampa.png" },
{ name: "Gargazampa", img: "gargazampa.png" },
{ name: "Aburroz", img: "aburroz.png" },
{ name: "Nomedá", img: "nomeda.png" },
{ name: "Opti", img: "opti.png" },
{ name: "Enerposa", img: "enerposa.png" },
{ name: "Eneposa", img: "eneposa.png" },
{ name: "Mejorposa", img: "mejorposa.png" },
{ name: "Vivariposa", img: "vivariposa.png" },
{ name: "Felisonte", img: "felisonte.png" },
{ name: "Reversa", img: "reversa.png" },
{ name: "Reversada", img: "reversada.png" },
{ name: "Tricotom", img: "tricotom.png" },
{ name: "Dádivo", img: "dadivo.png" },
{ name: "Bolilete", img: "bolilete.png" },
{ name: "Doblilete", img: "doblilete.png" },
{ name: "Papá Rayo", img: "papa_rayo.png" },
{ name: "Tío Infinito", img: "tio_infinito.png" },
{ name: "Mamá Aura", img: "mama_aura.png" },
{ name: "Tita Corazón", img: "tita_corazon.png" },
{ name: "Noguío", img: "noguio.png" },
{ name: "Topami", img: "topami.png" },
{ name: "Algio", img: "algio.png" },
{ name: "Agujeto", img: "agujeto.png" },
{ name: "Machaka", img: "machaka.png" },
{ name: "Negatisquito", img: "negatisquito.png" },
{ name: "Deprisquito", img: "deprisquito.png" },
{ name: "Picorrón", img: "picorron.png" },
{ name: "Nomevén", img: "nomeven.png" },
{ name: "Nostoy", img: "nostoy.png" },
{ name: "Nul", img: "nul_.png" },
{ name: "Enciélago", img: "encielago.png" },
{ name: "Caseriélago", img: "caserielago.png" },
{ name: "Ermiciélago", img: "ermicielago.png" },
{ name: "Suspicioni", img: "suspicioni.png" },
{ name: "Pataletoni", img: "pataletoni.png" },
{ name: "Contrarioni", img: "contrarioni.png" },
{ name: "Tengulecto", img: "tengulecto.png" },
{ name: "Tengullón", img: "tengullon.png" },
{ name: "Negasus", img: "negasus.png" },
{ name: "Pifiasus", img: "pifiasus.png" },
{ name: "Timidiablo", img: "timidiablo.png" },
{ name: "Osademonio", img: "osademonio.png" },
{ name: "Conde Caries", img: "conde_caries.png" },
{ name: "Avarqueroso", img: "avarqueroso.png" },
{ name: "Diablés", img: "diables.png" },
{ name: "Ejemtos", img: "ejemtos.png" },
{ name: "Erizlor", img: "erizlor.png" },
{ name: "Cartepollo", img: "cartepollo.png" },
{ name: "Rafaz", img: "rafaz.png" },
{ name: "Ayay", img: "ayay.png" },
{ name: "Horterraro", img: "horterraro.png" },
{ name: "Alarción", img: "alarcion.png" },
{ name: "Cantonio", img: "cantonio.png" },
{ name: "Multiniche", img: "multiniche.png" },
{ name: "Ser Bero", img: "ser_bero.png" },
{ name: "Goto", img: "goto.png" },
{ name: "Sirimiri", img: "sirimiri.png" },
{ name: "Copo", img: "copo.png" },
{ name: "Ventisquero", img: "ventisquero.png" },
{ name: "Coagulón", img: "coagulon.png" },
{ name: "Reboca", img: "reboca.png" },
{ name: "Pilicajosa", img: "pilicajosa.png" },
{ name: "Negatalia", img: "negatalia.png" },
{ name: "Cuesco", img: "cuesco.png" },
{ name: "Péditum", img: "peditum.png" },
{ name: "Graciosno", img: "graciosno.png" },
{ name: "Hilarión", img: "hilarion.png" },
{ name: "Arruñona", img: "arruñona.png" },
{ name: "Belladona", img: "belladona.png" },
{ name: "Eterna", img: "eterna.png" },
{ name: "Insomna", img: "insomna.png" },
{ name: "Morfea", img: "morfea.png" },
{ name: "Noko", img: "noko.png" },
{ name: "Florinoko", img: "florinoko.png" },
{ name: "Pandanoko", img: "pandanoko.png" },
{ name: "Anjijila", img: "anjijila.png" },
{ name: "Tenongrio", img: "tenongrio.png" },
{ name: "Urnaconda", img: "urnaconda.png" },
{ name: "Pezqueroso", img: "pezqueroso.png" },
{ name: "Pezgativo", img: "pezgativo.png" },
{ name: "Pezquiciado", img: "pezquiciado.png" },
{ name: "Draqui", img: "draqui.png" },
{ name: "Lord Dragón", img: "lord_dragon.png" },
{ name: "Dragón Azur", img: "dragon_azur.png" },
{ name: "Ido", img: "ido.png" },
{ name: "Turdido", img: "turdido.png" },
{ name: "Pellurón", img: "pelluron.png" },
{ name: "Pringurón", img: "pringuron.png" },
{ name: "Boquirroto", img: "boquirroto.png" },
{ name: "Yopago", img: "yopago.png" },
{ name: "Charlatón", img: "charlaton.png" },
{ name: "Tochaplátano", img: "tochaplatano.png" },
{ name: "Mandícoro", img: "mandicoro.png" },
{ name: "Ciniserpe", img: "ciniserpe.png" },
{ name: "Arfidio", img: "arfidio.png" },
{ name: "Venocto", img: "venocto.png" },
{ name: "Venoctoscuro", img: "venoctoscuro.png" },
{ name: "Shogunyan", img: "shogunyan.png" },
{ name: "Komasura", img: "komasura.png" },
{ name: "Dandiniche", img: "dandiniche.png" },
{ name: "Abuflorido", img: "abuflorido.png" },
{ name: "Dorantúo", img: "dorantuo.png" },
{ name: "Zafinyan", img: "zafinyan.png" },
{ name: "Esmenyan", img: "esmenyan.png" },
{ name: "Rubinyan", img: "rubinyan.png" },
{ name: "Topanyan", img: "topanyan.png" },
{ name: "Diamanyan", img: "diamanyan.png" },
{ name: "Babamandra", img: "babamandra.png" },
{ name: "Termascino", img: "termascino.png" },
{ name: "Bergantín", img: "bergantin.png" },
{ name: "Animanstruo", img: "animanstruo.png" },
{ name: "Fantasmurai", img: "fantasmurai.png" },
{ name: "Tarantutor", img: "tarantutor.png" },
{ name: "Dr. Majarov", aliases: ["dr. majarov", "dr majarov", "doctor majarov"], img: "dr._majarov.png" },
{ name: "McKraken", img: "mckraken.png" },
{ name: "McKraken", img: "mckraken_2.png" },
{ name: "Duoleta", img: "duoleta.png" },
{ name: "Cantaderna", img: "cantaderna.png" },
{ name: "Ojimandra", img: "ojimandra.png" },
{ name: "Jabalupo", img: "jabalupo.png" },
{ name: "Estigio VI", img: "estigio_vi.png" },
{ name: "Clipso", img: "clipso.png" },
{ name: "Dr. Sintripas", aliases: ["dr. sintripas", "dr sintripas", "doctor sintripas"], img: "dr._sintripas.png" },
{ name: "Terrormadura", img: "terrormadura.png" },
{ name: "Calarrupto", img: "calarrupto.png" },
{ name: "Caldewok", img: "caldewok.png" },
{ name: "Gargantúo", img: "gargantuo.png" },
{ name: "Cazamentires", img: "cazamentires.png" },
{ name: "Demoniorco", img: "demoniorco.png" },
{ name: "Milimpiano", img: "Milimpiano.png" },
    { name: "Samulimpio", img: "Samulimpio.png" },
    { name: "Dormileón", img: "Dormileon.png" },
    { name: "León Alfa", img: "Leon_Alfa.png" },
    { name: "Pataleto", img: "Pataleto.png" },
    { name: "Chupatinas", img: "Chupatinas.png" },
    { name: "Cortarroz", img: "Cortarroz.png" },
    { name: "Socarrat", img: "Socarrat.png" },
    { name: "Atierrador", img: "Atierrador.png" },
    { name: "Capi-Cachas", img: "Capi-Cachas.png" },
    { name: "Devoramonios", img: "Devoramonios.png" },
    { name: "Devoralmas", img: "Devoralmas.png" },
    { name: "Fracaguas", img: "Fracaguas.png" },
    { name: "Chancleto", img: "Chancleto.png" },
    { name: "Komecasa", img: "Komecasa.png" },
    { name: "Sincara", img: "Sincara.png" },
    { name: "Losiento", img: "Losiento.png" },
    { name: "Domiplof", img: "Domiplof.png" },
    { name: "Niebli", img: "Niebli.png" },
    { name: "Nébula", img: "Nebula.png" },
    { name: "Don Kaldo", img: "Don_Kaldo.png" },
    { name: "Falsillo", img: "Falsillo.png" },
    { name: "Apelicano", img: "Apelicano.png" },
    { name: "Trielespejo", img: "Trielespejo.png" },
    { name: "Ambrosio", img: "Ambrosio.png" },
    { name: "Kimera", img: "Kimera.png" },
    { name: "Kimerreal", img: "Kimerreal.png" },
    { name: "Aterracota", img: "Aterracota.png" },
    { name: "Quierodeso", img: "Quierodeso.png" },
    { name: "Gambulloso", img: "Gambulloso.png" },
    { name: "Indiligencio", img: "Indiligencio.png" },
    { name: "Tanquivocado", img: "Tanquivocado.png" },
    { name: "Mimoniquí", img: "Mimoniqui.png" },
    { name: "Mamuguanto", img: "Mamuguanto.png" },
    { name: "Rayael", img: "Rayael.png" },
    { name: "Cazarayos", img: "Cazarayos.png" },
    { name: "Zudado", img: "Zudado.png" },
    { name: "Eleganfibio", img: "Eleganfibio.png" },
    { name: "Frikigarto", img: "Frikigarto.png" },
    { name: "Patis", img: "Patis.png" },
    { name: "Picassina", img: "Picassina.png" },
    { name: "Chíclope", img: "Chiclope.png" },
    { name: "Buchinyan", img: "Buchinyan.png" },
    { name: "Somnia", img: "Somnia.png" },
    { name: "Cellisca", img: "Cellisca.png" },
    { name: "Rapidizo", img: "Rapidizo.png" },
    { name: "Oso Boco", img: "Oso_Boco.png" },
    { name: "Kappafalso", img: "Kappafalso.png" },
    { name: "Tigrappa", img: "Tigrappa.png" },
    { name: "Gran Mangu", img: "Gran_Mangu.png" },
    { name: "Algacabana", img: "Algacabana.png" },
    { name: "Níscala", img: "Niscala.png" },
    { name: "Curaníscala", img: "Curaniscala.png" },
    { name: "Arenito", img: "Arenito.png" },
    { name: "Don Arenito", img: "Don_Arenito.png" },
    { name: "Sombrillo", img: "Sombrillo.png" },
    { name: "Sombrillogro", img: "Sombrillogro.png" },
    { name: "Paupermán", img: "Pauperman.png" },
    { name: "Nomi", img: "Nomi.png" },
    { name: "Gran Nomi", img: "Gran_Nomi.png" },
    { name: "Torivinador", img: "Torivinador.png" },
    { name: "Torivino", img: "Torivino.png" },
    { name: "DON-CHAN", aliases: ["DON-CHAN", "Don chan"], img: "Don-chan.png" },
    { name: "Rayito", img: "Rayito.png" },
    { name: "Kyryn", img: "Kyryn.png" },
    { name: "Unikyryn", img: "Unikyryn.png" },
    { name: "Envelo", img: "Envelo.png" },
    { name: "Cafeíno", img: "Cafeino.png" },
    { name: "Acelgo", img: "Acelgo.png" },
    { name: "Morenaso", img: "Morenaso.png" },
    { name: "Prestragón", img: "Prestragon.png" },
    { name: "Bolsadrón", img: "Bolsadron.png" },
    { name: "Espaoi", img: "Espaoi.png" },
    { name: "Hazlotú", img: "Hazlotu.png" },
    { name: "Záppingla", img: "Zappingla.png" },
    { name: "Rataleza", img: "Rataleza.png" },
    { name: "Frivolia", img: "Frivolia.png" },
    { name: "Babamandra", img: "Babamandra_A.png" },
    { name: "Dracunyan", img: "Dracunyan.png" },
    { name: "Ojezno", img: "Ojezno.png" },
    { name: "Joyezno", img: "Joyezno.png" },
    { name: "Caldewok", img: "Caldewok_A.png" },
    { name: "Mirlobirlo", img: "Mirlobirlo.png" },
    { name: "Estréquito", img: "Estrequito.png" },
    { name: "Vrumbo", img: "Vrumbo.png" },
    { name: "Peluco", img: "Peluco.png" },
    { name: "Foliculio", img: "Foliculio.png" },
    { name: "No-No", img: "No-No.png" },
    { name: "Batallitos", img: "Batallitos.png" },
    { name: "Eskakeo", img: "Eskakeo.png" },
    { name: "Lena", img: "Lena.png" },
    { name: "Malena", img: "Malena.png" },
    { name: "Termascino", img: "Termascino_A.png" },
    { name: "Aracnio", img: "Aracnio.png" },
    { name: "Aracne", img: "Aracne.png" },
    { name: "Tortícolis", img: "Torticolis.png" },
    { name: "Malmet", img: "Malmet.png" },
    { name: "Agorerana", img: "Agorerana.png" },
    { name: "Desolvidador", img: "Desolvidador.png" },
    { name: "Memorio", img: "Memorio.png" },
    { name: "Mosquereta", img: "Mosquereta.png" },
    { name: "Bronquereta", img: "Bronquereta.png" },
    { name: "Nereida", img: "Nereida.png" },
    { name: "Sirenia", img: "Sirenia.png" },
    { name: "Oceánida", img: "Oceanida.png" },
    { name: "Cisnia", img: "Cisnia.png" },
    { name: "Vacilagón", img: "Vacilagon.png" },
    { name: "Bergantín", img: "Bergantin_A.png" },
    { name: "Chafarina", img: "Chafarina.png" },
    { name: "Repeloso", img: "Repeloso.png" },
    { name: "Octosierpe", img: "Octosierpe.png" },
    { name: "Melonyan", img: "Melonyan.png" },
    { name: "Naranyan", img: "Naranyan.png" },
    { name: "Kiwinyan", img: "Kiwinyan.png" },
    { name: "Uvanyan", img: "Uvanyan.png" },
    { name: "Fresanyan", img: "Fresanyan.png" },
    { name: "Sandinyan", img: "Sandinyan.png" },
    { name: "Robokapp", img: "Robokapp.png" },
    { name: "Robokoma", img: "Robokoma.png" },
    { name: "Roboabuzampa", img: "Roboabuzampa.png" },
    { name: "Robocantonio", img: "Robocantonio.png" },
    { name: "Robonoko", img: "Robonoko.png" },
    { name: "Robodraqui", img: "Robodraqui.png" },
    { name: "Maravinyan", img: "Maravinyan.png" },
    { name: "Robonyan 2.0", img: "Robonyan_2.0.png" },
    { name: "Sailornyan", img: "Sailornyan.png" },
    { name: "Tigrenyan", img: "Tigrenyan.png" },
    { name: "Hovernyan", img: "Hovernyan.png" },
    { name: "Darknyan", img: "Darknyan.png" },
    { name: "Jibakoma", img: "Jibakoma.png" },
    { name: "Jetnyan", img: "Jetnyan.png" },
    { name: "Injustio", img: "Injustio.png" },
    { name: "Malicia", img: "Malicia.png" },
    { name: "Implacablio", img: "Implacablio.png" },
    { name: "Inaguantablio", img: "Inaguantablio.png" },
    { name: "Destrukto", img: "Destrukto.png" },
    { name: "Chupatodo", img: "Chupatodo.png" },
    { name: "Aterrahorror", img: "Aterrahorror.png" },
    { name: "Apéstula", img: "Apestula.png" },
    { name: "Kappamalo", img: "Kappamalo.png" },
    { name: "Sombrío", img: "Sombrio.png" },
    { name: "Pillastre", img: "Pillastre.png" },
    { name: "Toragorero", img: "Toragorero.png" },
    { name: "Cardado", img: "Cardado.png" },
    { name: "Trampeida", img: "Trampeida.png" },
    { name: "Malisnia", img: "Malisnia.png" },
    { name: "Keji Do Khan", img: "Keji_Do_Khan.png" },
    { name: "Gruñón Khan", img: "Gruñon_Khan.png" },
    { name: "Puergazán", img: "Puergazan.png" },
    { name: "Torreznio", img: "Torreznio.png" },
    { name: "Pupilo Panja", img: "Pupilo_Panja.png" },
    { name: "Panja Pro", img: "Panja_Pro.png" },
    { name: "Samuranguila", img: "Samuranguila.png" },
    { name: "Anguilocio", img: "Anguilocio.png" },
    { name: "Minipulpobola", img: "Minipulpobola.png" },
    { name: "Pulpobola Rey", img: "Pulpobola_Rey.png" },
    { name: "Aranecido", img: "Aranecido.png" },
    { name: "Desaranecido", img: "Desaranecido.png" },
    { name: "Sumodón", img: "Sumodon.png" },
    { name: "Supersumodón", img: "Supersumodon.png" },
    { name: "Desinverest", img: "Desinverest.png" },
    { name: "Inverestupción", img: "Inverestupcion.png" },
    { name: "Contentallo", img: "Contentallo.png" },
    { name: "Talloestrella", img: "Talloestrella.png" },
    { name: "Tripasqueleto", img: "Tripasqueleto.png" },
    { name: "Meganyan", img: "Meganyan.png" },
    { name: "Capitán Penas", img: "Capitan_Penas.png" },
    { name: "Cicluracán", img: "Cicluracan.png" },
    { name: "Áurea", img: "Aurea.png" },
    { name: "Argenta", img: "Argenta.png" },
    { name: "Lady Desdicha", img: "Lady_Desdicha.png" },
    { name: "Lady Démona", img: "Lady_Demona.png" },
    { name: "Manojo", img: "Manojo.png" },
    { name: "Torbellóptico", img: "Torbelloptico.png" },
    { name: "Martillete", img: "Martillete.png" },
    { name: "Capipalante", img: "Capipalante.png" },
    { name: "Pili", img: "Pili.png" },
    { name: "Mili", img: "Mili.png" },
    { name: "Lady Espanto", img: "Lady_Espanto.png" },
    { name: "Kali Mera", img: "Kali_Mera.png" },
    { name: "Aureosqueleto", img: "Aureosqueleto.png" },
    { name: "Diamanqueleto", img: "Diamanqueleto.png" },
    { name: "Manazas", img: "Manazas.png" },
    { name: "Retinado", img: "Retinado.png" },
    { name: "Tomoko", img: "Tomoko.png" },
    { name: "Ultra N", img: "Ultra_N.png" },
    { name: "Ultra K", img: "Ultra_K.png" },
    { name: "Jibanyan S", img: "Jibanyan_S.png" },
    { name: "Komasan S", img: "Komasan_S.png" },
    { name: "Komajiro S", img: "Komajiro_S.png" },
    { name: "Oskyubi", img: "Oskyubi.png" },
    { name: "Iluminocto", img: "Iluminocto.png" },
    { name: "Gargantúo", img: "Gargantuo_A.png" },
    { name: "Cazamentires", img: "Cazamentires_A.png" },
    { name: "Demoniorco", img: "Demoniorco_A.png" },
    { name: "Rúbeo J", img: "Rubeo_J.png" },
    { name: "Gran Sabueso", img: "Gran_Sabueso.png" },
    { name: "Intelecto", img: "Intelecto.png" },
    { name: "Nulo", img: "Nulo.png" },
    { name: "Testructor", img: "Testructor.png" },
    { name: "Infinitio", img: "Infinitio.png" },
    { name: "Expresso", img: "Expresso.png" },
    { name: "Kabukio", img: "Kabukio.png" },
{ "name": "Pelirrojo", "img": "Pelirrojo.png" },
  { "name": "Grazi", "img": "Grazi.png" },
  { "name": "Usapyon", "img": "Usapyon.png" },
  { "name": "Usapyon", "img": "Usapyon_F.png" },
  { "name": "Usapyon", "img": "Usapyon_S.png" },
  { "name": "Usapyon", "img": "Usapyon_M.png" },
  { "name": "Usapyon", "img": "Usapyon_P.png" },
  { "name": "Whisper", "img": "Whisper.png" },
  { "name": "Whispócrates", aliases: ["Whispócrates", "Soldado Whispocrates"], "img": "Whispocrates.png" },
  { "name": "Jibanyan B", "img": "Jibanyan_B.png" },
  { "name": "Komasan B", "img": "Komasan_B.png" },
  { "name": "Sir Nyancelot", "img": "Sir_Nyancelot.png" },
  { "name": "Maginyan", "img": "Maginyan.png" },
  { "name": "Momonyan", "img": "Momonyan.png" },
  { "name": "Perronyan", "img": "Perronyan.png" },
  { "name": "Simionyan", "img": "Simionyan.png" },
  { "name": "Faisanyan", "img": "Faisanyan.png" },
  { "name": "Devoramonios", "img": "Devoramonios_B.png" },
  { "name": "Devoralmas", "img": "Devoralmas_B.png" },
  { "name": "Cotiterror", "img": "Cotiterror.png" },
  { "name": "Murmullamasa", "img": "Murmullamasa.png" },
  { "name": "Cremaligno", "img": "Cremaligno.png" },
  { "name": "Robonyan 28", "img": "Robonyan_28.png" },
  { "name": "Zarparroja", "img": "Zarparroja.png" },
  { "name": "Vueltomai", "img": "Vueltomai.png" },
  { "name": "Coman-cachas", "img": "Coman-cachas.png" },
  { "name": "Aracnéfico", "img": "Aracnefico.png" },
  { "name": "Belcefibio", "img": "Belcefibio.png" },
  { "name": "Normalino", aliases: ["Normalino", "Normalino2", "Normalino 2"], "img": "Normalino.png" },
  { "name": "Kintaronyan", "img": "Kintaronyan.png" },
  { "name": "Kabukio", "img": "Kabukio_A.png" },
  { "name": "Rúbeo J", "img": "Rubeo_J_A.png" },
  { "name": "Gran Sabueso", "img": "Gran_Sabueso_A.png" },
  { "name": "Alga Senséi", "img": "Alga_Sensei.png" },
  { "name": "Odisenyan", "img": "Odisenyan.png" },
  { "name": "Tripasqueleto", "img": "Tripasqueleto_A.png" },
  { "name": "Usapyon B", "img": "Usapyon_B.png" },
  { "name": "Tristeresa", "img": "Tristeresa.png" },
  { "name": "Estrenoko", "img": "Estrenoko.png" },
  { "name": "Gran Enma", "img": "Gran_Enma.png" },
  { "name": "Capitán Rayo", "img": "Capitan_Rayo.png" },
  { "name": "Capitán Rayo", "img": "Capitan_Rayo_S.png" },
  { "name": "Robonyan 3000", "img": "Robonyan_3000.png" },
  { "name": "Duque Lametodo", "img": "Duque_Lametodo.png" },
  { "name": "Chupatricio", "img": "Chupatricio.png" },
  { "name": "Zazel", "img": "Zazel.png" },
  { "name": "Zazelirio", "img": "Zazelirio.png" },
  { "name": "Zarpadorada", "img": "Zarpadorada.png" },
  { "name": "Vueltodorado", "img": "Vueltodorado.png" },
  { "name": "Intelecto Iluminado", "img": "Intelecto_Iluminado.png" },
  { "name": "Shogún Real", "img": "Shogun_Real.png" },
  { "name": "Emperador Rosa", "img": "Emperador_Rosa.png" },
{ "name": "Robin Ful", "img": "Robin_Ful.png" },
  { "name": "Tornalmohado", "img": "Tornalmohado.png" },
  { "name": "Gran Coco", "img": "Gran_Coco.png" },
  { "name": "Minimoto", "img": "Minimoto.png" },
  { "name": "Bola Blanda", "img": "Bola_Blanda.png" },
  { "name": "Bateadós", "img": "Bateados.png" },
  { "name": "Chupapremios", "img": "Chupapremios.png" },
  { "name": "Guerrero Güey", "img": "Guerrero_Guey.png" },
  { "name": "Huracán Güey", "img": "Huracan_Guey.png" },
  { "name": "Barbacoo", "img": "Barbacoo.png" },
  { "name": "Piopío Yonohesido", "img": "Piopio_Yonohesido.png" },
  { "name": "Globonauta", "img": "Globonauta.png" },
  { "name": "Shurikenny", "img": "Shurikenny.png" },
  { "name": "Nunchucky", "img": "Nunchucky.png" },
  { "name": "Camelia", "img": "Camelia.png" },
  { "name": "Cremallero", "img": "Cremallero.png" },
  { "name": "Metepatas", "img": "Metepatas.png" },
  { "name": "Mochueloqué", "img": "Mochueloque.png" },
  { "name": "Todoídos", "img": "Todoidos.png" },
  { "name": "Preguntio", "img": "Preguntio.png" },
  { "name": "Respondio", "img": "Respondio.png" },
  { "name": "Exitio", "img": "Exitio.png" },
  { "name": "Cachocarne", "img": "Cachocarne.png" },
  { "name": "Mazorco", "img": "Mazorco.png" },
  { "name": "Cascarito", "img": "Cascarito.png" },
  { "name": "Pomponio Gala", "img": "Pomponio_Gala.png" },
  { "name": "Fiestuki", "img": "Fiestuki.png" },
  { "name": "Calaveroscopio", "img": "Calaveroscopio.png" },
  { "name": "Leongüista", "img": "Leonguista.png" },
  { "name": "Estatiniño", "img": "Estatinino.png" },
  { "name": "Profesor Avertijo", "img": "Profesor_Avertijo.png" },
  { "name": "Noaipapel", "img": "Noaipapel.png" },
  { "name": "Jipigenio", "img": "Jipigenio.png" },
  { "name": "Miss Teria", "img": "Miss_Teria.png" },
  { "name": "Renaldo", "img": "Renaldo.png" },
  { "name": "Isotomas", "img": "Isotomas.png" },
  { "name": "Coneagente", "img": "Coneagente.png" },
  { "name": "Blancacone", "img": "Blancacone.png" },
  { "name": "Prudencio", "img": "Prudencio.png" },
  { "name": "Explotacota", "img": "Explotacota.png" },
  { "name": "Grafilcebú", "img": "Grafilcebu.png" },
  { "name": "Chocovaca", "img": "Chocovaca.png" },
  { "name": "Vacaloca", "img": "Vacaloca.png" },
  { "name": "Fracalavero", "img": "Fracalavero.png" },
  { "name": "Calabilidoso", "img": "Calabilidoso.png" },
  { "name": "Master Chof", "img": "Master_Chof.png" },
  { "name": "Monte Merario", "img": "Monte_Merario.png" },
  { "name": "Calmarinero", "img": "Calmarinero.png" },
  { "name": "Almirante Admirable", "img": "Almirante_Admirable.png" },
  { "name": "Peter Punki", "img": "Peter_Punki.png" },
  { "name": "Pantuflo", "img": "Pantuflo.png" },
  { "name": "Reahucio", "img": "Reahucio.png" },
  { "name": "Radiopatio", "img": "Radiopatio.png" },
  { "name": "Filete II", "img": "Filete_II.png" },
  { "name": "Showbonyan", "img": "Showbonyan.png" },
  { "name": "Tiburon Tiburcio", "img": "Tiburon_Tiburcio.png" },
  { "name": "Tiburon Jaqueton", "img": "Tiburon_Jaqueton.png" },
  { "name": "Capitan Nublo", "img": "Capitan_Nublo.png" },
  { "name": "Sincopollo", "img": "Sincopollo.png" },
  { "name": "Brownilda", "img": "Brownilda.png" },
  { "name": "Chapulin", "img": "Chapulin.png" },
  { "name": "Apanleado", "img": "Apanleado.png" },
  { "name": "Panduro", "img": "Panduro.png" },
  { "name": "Superniñato", "img": "Superninato.png" },
  { "name": "Superniñato Rebelde", "img": "Superninato_Rebelde.png" },
  { "name": "Superniñato Picajoso", "img": "Superninato_Picajoso.png" },
  { "name": "BellonZ", "img": "BellonZ.png" },
  { "name": "Olvirunner", "img": "Olvirunner.png" },
  { "name": "Gatallanes", "img": "Gatallanes.png" },
  { "name": "Limonescente", "img": "Limonescente.png" },
  { "name": "Tomanota", "img": "Tomanota.png" },
  { "name": "Zalameria", "img": "Zalameria.png" },
  { "name": "Jibanyan Liu Bei", "img": "Jibanyan_Liu_Bei.png" },
  { "name": "Komasan Sun Ce", "img": "Komasan_Sun_Ce.png" },
  { "name": "Todoapesta", "img": "Todoapesta.png" },
  { "name": "Relapache", "img": "Relapache.png" },
  { "name": "Cafechucho", "img": "Cafechucho.png" },
  { "name": "Partidacio", "img": "Partidacio.png" },
  { "name": "Tomnyan", "img": "Tomnyan.png" },
  { "name": "Komaestopistas", "img": "Komaestopistas.png" },
  { "name": "Segadora", "img": "Segadora.png" },
  { "name": "Chocobonyan", "img": "Chocobonyan.png" },
  { "name": "Mogurinyan", "img": "Mogurinyan.png" },
  { "name": "Wobblenyan", "img": "Wobblenyan.png" },
  { "name": "Wibblekoma", "img": "Wibblekoma.png" },
  { "name": "Sushinyan", "img": "Sushinyan.png" },
  { "name": "Tempurasan", "img": "Tempurasan.png" },
  { "name": "Tenguriginal", "img": "Tenguriginal.png" },
  { "name": "Angel Garudian", "img": "Angel_Garudian.png" },
  { "name": "Lenaciegotxea", "img": "Lenaciegotxea.png" },
  { "name": "Chunda y Tachunda", "img": "Chunda_y_Tachunda.png" },
  { "name": "Abuzampa XXL", "img": "Abuzampa_XXL.png" },
  { "name": "Albornocita Azul", "img": "Albornocita_Azul.png" },
  { "name": "Florentina", "img": "Florentina.png" },
  { "name": "Afronauta", "img": "Afronauta.png" },
  { "name": "Arrocet", "img": "Arrocet.png" },
  { "name": "Espe", "img": "Espe.png" },
  { "name": "Bellotieso", "img": "Bellotieso.png" },
  { "name": "Clican", "img": "Clican.png" },
  { "name": "Indeciguro", "img": "Indeciguro.png" },
  { "name": "Trabalanghi", "img": "Trabalanghi.png" },
  { "name": "Dormidomingo", "img": "Dormidomingo.png" },
  { "name": "Auxiliadora", "img": "Auxiliadora.png" },
  { "name": "Abuflauta", "img": "Abuflauta.png" },
  { "name": "Gememinencias", "img": "Gememinencias.png" },
  { "name": "Repostilleja", "img": "Repostilleja.png" },
  { "name": "Gogonzalo", "img": "Gogonzalo.png" },
  { "name": "Esmaltina", "img": "Esmaltina.png" },
  { "name": "Fantasfitriona", "img": "Fantasfitriona.png" },
  { "name": "Sonico", "img": "Sonico.png" },
  { "name": "Supersonico", "img": "Supersonico.png" },
  { "name": "Berenpenas", "img": "Berenpenas.png" },
  { "name": "Akusika", "img": "Akusika.png" },
  { "name": "Leonerai", "img": "Leonerai.png" },
  { "name": "Trenditopico", "img": "Trenditopico.png" },
  { "name": "Retuiterio", "img": "Retuiterio.png" },
  { "name": "Panceto", "img": "Panceto.png" },
  { "name": "Bilgatino", "img": "Bilgatino.png" },
  { "name": "Su Hackeltad", "img": "Su_Hackeltad.png" },
  { "name": "Rey Pulsivo", "img": "Rey_Pulsivo.png" },
  { "name": "Timo Gallo", "img": "Timo_Gallo.png" },
  { "name": "Rocky Malrolla", "img": "Rocky_Malrolla.png" },
  { "name": "Hierodista", "img": "Hierodista.png" },
  { "name": "Herrato", "img": "Herrato.png" },
  { "name": "MC Kappa", "img": "MC_Kappa.png" },
  { "name": "Tumbardillo", "img": "Tumbardillo.png" },
  { "name": "Usapyon Zhongda", "img": "Usapyon_Zhongda.png" },
  { "name": "Dr. Nihil Listo", "img": "Dr_Nihil_Listo.png" },
  { "name": "Dr. Nocturnia", "img": "Dr_Nocturnia.png" },
  { "name": "Espaya", "img": "Espaya.png" },
  { "name": "Corbapacasa", "img": "Corbapacasa.png" },
  { "name": "Cartairada", "img": "Cartairada.png" },
  { "name": "Ambivalencio", "img": "Ambivalencio.png" },
  { "name": "Lapo", "img": "Lapo.png" },
  { "name": "Dabombo", "img": "Dabombo.png" },
  { "name": "Los Bomboledores", "img": "Los_Bomboledores.png" },
  { "name": "Amarilia", "img": "Amarilia.png" },
  { "name": "Sheriff Agonio", "img": "Sheriff_Agonio.png" },
  { "name": "Padefo", "img": "Padefo.png" },
  { "name": "Sololo", "img": "Sololo.png" },
  { "name": "Maracario", "img": "Maracario.png" },
  { "name": "Pandalon", "img": "Pandalon.png" },
  { "name": "Peluson", "img": "Peluson.png" },
  { "name": "Amarguito", "img": "Amarguito.png" },
  { "name": "Nauseo", "img": "Nauseo.png" },
  { "name": "Condespotico", "img": "Condespotico.png" },
  { "name": "Flequipilante", "img": "Flequipilante.png" },
  { "name": "Origenio", "img": "Origenio.png" },
  { "name": "Horrogenio", "img": "Horrogenio.png" },
  { "name": "Fulgurilla", "img": "Fulgurilla.png" },
  { "name": "Saltetera", "img": "Saltetera.png" },
  { "name": "Don Despacito", "img": "Don_Despacito.png" },
  { "name": "Sierpesado", "img": "Sierpesado.png" },
  { "name": "Cobravil", "img": "Cobravil.png" },
  { "name": "Aymadrilo", "img": "Aymadrilo.png" },
  { "name": "Naqueperder", "img": "Naqueperder.png" },
  { "name": "Borjamar", "img": "Borjamar.png" },
  { "name": "Bebesaurio", "img": "Bebesaurio.png" },
  { "name": "Destrozasaurio", "img": "Destrozasaurio.png" },
  { "name": "Torpesaurio", "img": "Torpesaurio.png" },
  { "name": "Luigi Longueras", "img": "Luigi_Longueras.png" },
  { "name": "Pulpopular", "img": "Pulpopular.png" },
  { "name": "Tentanfadado", "img": "Tentanfadado.png" },
  { "name": "Tochacolate", "img": "Tochacolate.png" },
  { "name": "Sustoleo", "img": "Sustoleo.png" },
  { "name": "Reptozudo", "img": "Reptozudo.png" },
  { "name": "Saporientador", "img": "Saporientador.png" },
  { "name": "Originyan", "img": "originyan.gif" },
  { "name": "Aydroide Y", "img": "Aydroide_Y.png" },
  { "name": "Rey Jibanyan", "img": "Rey_Jibanyan.png" },
  { "name": "Reina Usapyon", "img": "Reina_Usapyon.png" },
  { "name": "Jotamasan", "img": "Jotamasan.png" },
  { "name": "Diez de Komajiro", "img": "Diez_de_Komajiro.png" },
  { "name": "Asnyan", "img": "Asnyan.png" },
  { "name": "Whismodin", "img": "Whismodin.png" },
  { "name": "Benzaiten", "img": "Benzaiten.png" },
  { "name": "Hotei", "img": "Hotei.png" },
  { "name": "Daikokuten", "img": "Daikokuten.png" },
  { "name": "Ebisu", "img": "Ebisu.png" },
  { "name": "Bishamonten", "img": "Bishamonten.png" },
  { "name": "Gatobal Colon", "img": "Gatobal_Colon.png" },
  { "name": "T. Energison", "img": "T_Energison.png" },
  { "name": "Darguin", "img": "Darguin.png" },
  { "name": "Ultimo Nyanmurai", "img": "Ultimo_Nyanmurai.png" },
  { "name": "Koma Estrella", "img": "Koma_Estrella.png" },
  { "name": "Platinum", "img": "Platinum.png" },
  { "name": "Abusplendido", "img": "Abusplendido.png" },
  { "name": "Re-Q-Pera", "img": "Re-Q-Pera.png" },
  { "name": "Divamarina", "img": "Divamarina.png" },
  { "name": "Todobelicoso", "img": "Todobelicoso.png" },
  { "name": "Terminyanator", "img": "Terminyanator.png" },
  { "name": "Supernyan", "img": "Supernyan.png" },
  { "name": "Hovernyan S", "img": "Hovernyan_S.png" },
  { "name": "Hovernyan Cao Cao", "img": "Hovernyan_Cao_Cao.png" },
  { "name": "Yoguididacta", "img": "Yoguididacta.png" },
  { "name": "Frauduralla", "img": "Frauduralla.png" },
  { "name": "Insaciablo", "img": "Insaciablo.png" },
  { "name": "Penancio", "img": "Penancio.png" },
  { "name": "Venoctobot", "img": "Venoctobot.png" },
  { "name": "Demoniorco Lu Bu", "img": "Demoniorco_Lu_Bu.png" },
  { "name": "Kyubot", "img": "Kyubot.png" },
  { "name": "Robonyan Definitivo", "img": "Robonyan_Definitivo.png" },
  { "name": "Topiña", "img": "Topina.png" },
  { "name": "Miss Mousse", "img": "Miss_Mousse.png" },
  { "name": "Populina", "img": "populina.gif" },
  { "name": "Koalanyan", "img": "Koalanyan.png" },
  { "name": "Jibanyan T", "img": "jibanyan_T.gif" },
  { "name": "Komasan T", "img": "komasan_T.gif" },
  { "name": "Yemajestad", "img": "Yemajestad.png" },
  { "name": "Cicloman", "img": "Cicloman.png" },
  { "name": "Deporchugo", "img": "Deporchugo.png" },
  { "name": "Timorato Buendia", "img": "Timorato_Buendia.png" },
  { "name": "Maripasada", "img": "Maripasada.png" },
  { "name": "Ulteria", "img": "Ulteria.png" },
  { "name": "Milperdones", "img": "Milperdones.png" },
  { "name": "Angustianima", "img": "Angustianima.png" },
  { "name": "Cutremomia", "img": "Cutremomia.png" },
  { "name": "Kapman", "img": "Kapman.png" },
  { "name": "Tofupyon", "img": "Tofupyon.png" },
  { "name": "Dex Capito", "img": "Dex_Capito.png" },
  { "name": "Embajador Fabuloso", "img": "Embajador_Fabuloso.png" },
  { "name": "Intelecto", "img": "Intelecto_A.png" },
  { "name": "Zazel", "img": "Zazel_A.png" },
  { "name": "Procrastinocho", "img": "Procrastinocho.png" },
  { "name": "Cofre Cafre", "img": "Cofre_Cafre.png" },
  { "name": "Coco Masiel", "img": "Coco_Masiel.png" },
  { "name": "Whisper Kongming", "img": "Whisper_Kongming.png" },
  { "name": "Jurojin", "img": "Jurojin.png" },
  { "name": "Fukurokuju", "img": "Fukurokuju.png" },
  { "name": "Maldenotep", "img": "Maldenotep.png" },
  { "name": "Rey Palmiro", "img": "Rey_Palmiro.png" },
  { "name": "Pandora", "img": "Pandora.png" },
  { "name": "Ingenio", "img": "Ingenio.png" },
  { "name": "Bastenyan", "img": "Bastenyan.png" },
  { "name": "Komanubis", "img": "Komanubis.png" },
  { "name": "Discursi", "img": "Discursi.png" },
  { "name": "Educoso", "img": "Educoso.png" },
  { "name": "Lord Pedigri", "img": "Lord_Pedigri.png" },
  { "name": "Urbasierpe", "img": "Urbasierpe.png" },
  { "name": "Pregundragon Rey", "img": "Pregundragon_Rey.png" },
  { "name": "Zazel Justiciero", "img": "Zazel_Justiciero.png" },
  { "name": "Intelecto Iluminado", "img": "Intelecto_Iluminado_A.png" },
  { "name": "Enma Ancestral", "img": "Enma_Ancestral.png" },
  { "name": "Gran Enma Iluminado", "img": "Gran_Enma_Iluminado.png" },
  { "name": "Rollaculo", "img": "Rollaculo.png" },
  { "name": "Maharazas", "img": "Maharazas.png" },
  { "name": "Cimbalina", "img": "Cimbalina.png" },
  { "name": "Masculloso", "img": "Masculloso.png" },
  { "name": "Vociferio", "img": "Vociferio.png" },
  { "name": "Aviguito Pio", "img": "Aviguito_Pio.png" },
  { "name": "Frustrolillo", "img": "Frustrolillo.png" },
  { "name": "Bovida", "img": "Bovida.png" },
  { "name": "Equinio", "img": "Equinio.png" },
  { "name": "Pecificador", "img": "Pecificador.png" },
  { "name": "Alpina", "img": "Alpina.png" },
  { "name": "Seleno", "img": "Seleno.png" },
  { "name": "KJ", "img": "KJ.png" },
  { "name": "Enma Solar", "img": "Enma_Solar.png" },
  { "name": "Enma Infinito", "img": "Enma_Infinito.png" },
  { "name": "Enma Umbrio", "img": "Enma_Umbrio.png" },
  { "name": "Tibu Jones", "img": "tibu_Jones.gif" },
  { "name": "Vulcavador", "img": "vulcavador.gif" },
  { "name": "Adoleszombi", "img": "adoleszombi.gif" },
  { "name": "Nyanses II", "img": "nyanses_II.gif" },
  { "name": "Miopatra", "img": "Miopatra.png" },
  { "name": "Mazado de la Calzada", "img": "mazado_de_la_Calzada.gif" },
  { "name": "Dradorado", "img": "Dradorado.png" },
  { "name": "Fenixtelecto", "img": "Fenixtelecto.png" },
  { "name": "Chatarrenstein", "img": "Chatarrenstein.png" },
  { "name": "Supergerente", "img": "Supergerente.png" },
  { "name": "Ilusionisto", "img": "Ilusionisto.png" },
  { "name": "Camorro", "img": "Camorro.png" },
  { "name": "Diavolo", "img": "Diavolo.png" },
  { "name": "Flautista de Malmelin", "img": "Flautista_de_Malmelin.png" },
  { "name": "Gamero", "img": "Gamero.png" },
  { "name": "Yopple-Bot", "img": "Yopple-Bot.png" },
  { "name": "No-Bot", "img": "No-Bot.png" },
  { "name": "Nocturnia", "img": "Nocturnia.png" },
  { "name": "Ray Baqueto", "img": "Ray_Baqueto.png" },
  { "name": "Don Crueleone", "img": "Don_Crueleone.png" },
  { "name": "Don Conspirazione", "img": "Don_Conspirazione.png" },
  { "name": "Flautiscolito", "img": "Flautiscolito.png" },
  { "name": "Duocolito", "img": "Duocolito.png" },
  { "name": "Cantacolito", "img": "Cantacolito.png" },
  { "name": "Ciclonojo", "img": "Ciclonojo.png" },
  { "name": "Caballero Hueco", "img": "Caballero_Hueco.png" },
  { "name": "Paticio", "img": "Paticio.png" },
  { "name": "Demoniorcolito", "img": "Demoniorcolito.png" },
  { "name": "Iluminazen", "img": "Iluminazen.png" },
  { "name": "Capitan Botin", "img": "Capitan_Botin.png" },
  { "name": "Chef Ricote", "img": "Chef_Ricote.png" },
  { "name": "Doncella de la Ruina", "img": "Doncella_de_la_Ruina.png" },
  { "name": "Necrocobra", "img": "Necrocobra.png" },
  { "name": "Don Aureone", "img": "Don_Aureone.png" },
  { "name": "Icarus", "img": "Icarus.png" },
  { "name": "Ballenato", "img": "Ballenato.png" },
  { "name": "Cachaslote", "img": "Cachaslote.png" },
  { "name": "El Carnicero", "img": "El_Carnicero.png" },
  { "name": "Topoderoso", "img": "Topoderoso.png" },
  { "name": "El Ultimisimo Nyanmurai", "img": "El_Ultimisimo_Nyanmurai.png" },
 { name: "Ogamitaoshi", img: "Ogamitaoshi.png" },
    { name: "Capitán Dodo", aliases: ["Capitán Dodo", "Captain Dodo"], img: "Capitan_Dodo.png" },
    { name: "Chousensha", img: "Chosensha.png" },
    { name: "Monomaneking", img: "Monomaneking.png" },
    { name: "Morigami Rex", img: "Morigami_Rex.png" },
    { name: "Wibblejiro", aliases: ["Wibblejiro", "Wobblejiro", "Punijiro"], img: "Wibblejiro.png" },
    { name: "Shourinji", img: "Shourinji.png" },
    { name: "Raise Girl", img: "Raise_Girl.png" },
    { name: "Katenshi", img: "Katenshi.png" },
    { name: "Futekusaru", img: "Futekusaru.png" },
    { name: "Usapyon T", aliases: ["Usapyon T", "T-Usapyon"], img: "Usapyon_T.png" },
    { name: "Maizo Tokugawa", img: "Maizo_Tokugawa.png" },
    { name: "Al Baccino", aliases: ["Al Baccino", "Are Bacchino"], img: "Al_Baccino.png" },
    { name: "Tripasqueleto T", aliases: ["Tripasqueleto T", "Gashadokuro T"], img: "Tripasqueleto_T.png" },
    { name: "Kaneuki-hime", img: "Kaneuki-hime.png" },
    { name: "AkiraMEN", img: "AkiraMEN.png" },
    { name: "Omoutsubo", img: "Omoutsubo.png" },
    { name: "Naga Raja", img: "Naga_Raja.png" },
    { name: "Tribu Doyagari", aliases: ["Tribu Doyagari", "Doyagari-zoku"], img: "Tribu_Doyagari.png" },
    { name: "Doya Osa", img: "Doya_Osa.png" },
    { name: "Vascoda Gama", img: "Vascoda_Gama.png" },
    { name: "Shogunyan Cristal", aliases: ["Shogunyan Cristal", "Crystal Shogunyan"], img: "Shogunyan_Cristal.png" },
    { name: "Wobblehover", aliases: ["Wobblehover", "Wibblehover", "Punifuyu"], img: "Wobblehover.png" },
    { name: "Jibanyan T G", aliases: ["Jibanyan T G", "T-Jibanyan G"], img: "Jibanyan_T_G.png" },
    { name: "Jibanyan D", img: "Jibanyan_D.png" },
    { name: "Komasan T G", aliases: ["Komasan T G", "T-Komasan G"], img: "Komasan_T_G.png" },
    { name: "Komasan D", img: "Komasan_D.png" },
    { name: "Tibu Jones G", aliases: ["Tibu Jones G", "Indy Jaws G"], img: "Tibu_Jones_G.png" },
    { name: "Cindy Jaws", img: "Cindy_Jaws.png" },
    { name: "Vulcavador G", aliases: ["Vulcavador G", "Mr. Scoop G"], img: "Vulcavador_G.png" },
    { name: "Adoleszombi G", aliases: ["Adoleszombi G", "Zom B Chopper G"], img: "Adoleszombi_G.png" },
    { name: "Nyansés II G", aliases: ["Nyansés II G", "Neko II G"], img: "Nyanses_II_G.png" },
    { name: "Yodelsen", img: "Yodelsen.png" },
    { name: "Narciso II", aliases: ["Narciso II", "Narcis II"],img: "Narciso_II.png" },
    { name: "Zappadokia", img: "Zappadokia.png" },
    { name: "Mademoaiselle", img: "Mademoaiselle.png" },
    { name: "Piedra Rosetta", aliases: ["Piedra Rosetta", "Rosetta Stone"], img: "Piedra_Rosetta.png" },
    { name: "Doescalibur", img: "Doescalibur.png" },
    { name: "Encore Dead", img: "Encore_Dead.png" },
    { name: "Armaterasu", aliases: ["Armaterasu", "Armorterasu", "Amaterasu"], img: "Armaterasu.png" },
    { name: "Dandory", img: "Dandory.png" },
    { name: "Spatto", img: "Spatto.png" },
    { name: "Tanto", img: "Tanto.png" },
    { name: "Kirene", img: "Kirene.png" },
    { name: "Toranka", img: "Toranka.png" },
    { name: "Catleen", img: "Catleen.gif" },
    { name: "Gustaf", img: "Gustaf.png" },
    { name: "Gowin", img: "Gowin.png" },
    { name: "Seirei Banbarayar", img: "Seirei_Banbarayar.png" },
    { name: "Enma", img: "Enma.png" },
    { name: "Enma Oscuro", aliases: ["Enma Oscuro", "Yami Enma"], img: "Enma_Oscuro.png" },
    { name: "Lord Ananta", img: "Lord_Ananta.png" },
    { name: "Enma Meiou Maka", img: "Enma_Meiou_Maka.png" },
    { name: "Enmanyan", aliases: ["Enmanyan", "Enma Neko'ou Matatabi"], img: "Enmanyan.png" },
    { name: "Enma Ryuuou Mizuchi", img: "Enma_Ryuuou_Mizuchi.png" },
    { name: "Enma Raou Tekakku", img: "Enma_Raou_Tekakku.png" },
    { name: "Lord Acala", img: "Lord_Acala.png" },
    { name: "Chi Ma Tree", img: "Chi_Ma_Tree.png" },
    { name: "BaiKING", img: "BaiKING.png" },
    { name: "Boogiemum", img: "Boogiemum.png" },
    { name: "Kanibouzu", img: "Kanibouzu.png" },
    { name: "Orifalcon", img: "Orifalcon.png" },
    { name: "WaNEWdo", img: "WaNEWdo.png" },
    { name: "Dark Master", img: "Dark_Master.png" },
    { name: "Billy el Errante", aliases: ["Billy el Errante", "Sasurai no Billy"], img: "Billy_el_Errante.png" },
    { name: "Gowin", img: "Gowin_B.png" },
    { name: "Kanaendesu", img: "Kanaendesu.png" },
    { name: "Majin Banbarayar", img: "Majin_Banbarayar.png" },
    { name: "Yodelsen", img: "Yodelsen_B.png" },
    { name: "Zircondor", img: "Zircondor.png" },
     { "name": "Jabow", "img": "Jabow.png" },
  { "name": "Shirokuma", "img": "Shirokuma.png" },
  { "name": "Punkupine", "img": "Punkupine.png" },
  { "name": "Sorrypus", "img": "Sorrypus.png" },
  { "name": "McKraken", "img": "McKraken.png" },
  { "name": "Abuzampa", "img": "Abuzampa.gif" },
  { "name": "Pakkun", aliases: ["Pakkun", "Gabriel"], "img": "Pakkun.gif" },
  { "name": "Kyunshii", aliases: ["Kyunshii", "Zukkyunshii"], "img": "Kyunshii.gif" },
  { "name": "Hare-onna", aliases: ["Hare-onna", "Ame-onna"], "img": "Hare-onna.gif" },
  { "name": "Kakurenbou", aliases: ["Kakerenbou", "Inaiinaibaa"], "img": "Kakurenbou.gif" },
  { "name": "Granizia", "img": "Granizia.gif" },
  { "name": "Damona", "img": "Damona.gif" },
  { "name": "Zazel", "img": "Zazel_2040.png" },
  { "name": "Daniel", aliases: ["Daniel", "Big Danny"], "img": "Daniel.gif" },
  { "name": "Choky", aliases: ["Choky", "Shiomaneki"], "img": "Choky.gif" },
  { "name": "Flamileon", "img": "Flamileon.gif" },
  { "name": "Itashikatanashi", aliases: ["Itashikatanashi", "Yamuwoen"], "img": "Itashikatanashi.gif" },
  { "name": "Saya", aliases: ["Saya", "Makenki"], "img": "Saya.gif" },
  { "name": "Papa Rayo", "img": "Papa_Rayo.gif" },
  { "name": "Venocto", "img": "Venocto.gif" },
  { "name": "Venoctoscuro", "img": "Venoctoscuro.gif" },
  { "name": "Shogunyan", "img": "Shogunyan.gif" },
  { "name": "Komasura", "img": "Komasura.gif" },
  { "name": "Aracnio", "img": "Aracnio.gif" },
  { "name": "Lil' Acala", aliases: ["Lil' Acala", "Lil Acala", "Peque Acala"], "img": "Lil'_Acala.png" },
  { "name": "Honmaguro-taisho", aliases: ["Honmaguro-taisho", "Magulodon", "Neptuna"], "img": "Honmaguro-taisho.gif" },
  { "name": "Semicolon", aliases: ["Semicolon", "Semirongu", "Bugaboo"], "img": "Semicolon.gif" },
  { "name": "Komasan", "img": "Komasan.gif" },
  { "name": "Komajiro", "img": "Komajiro.gif" },
  { "name": "Banchou", aliases: ["Banchou", "Bourei Banchou", "Basher"], "img": "Banchou.gif" },
  { "name": "Noko", "img": "Noko.gif" },
  { "name": "Dragon Azur", "img": "Dragon_Azur.gif" },
  { "name": "Fuu-kun", aliases: ["Fuu-kun", "Fuujin"], "img": "Fuu-kun.gif" },
  { "name": "Rai-chan", aliases: ["Rai-chan", "Raijin"], "img": "Rai-chan.gif" },
  { "name": "Eleganfibio", "img": "Eleganfibio.gif" },
  { "name": "Jibanyan", "img": "Jibanyan.gif" },
  { "name": "Uribou", aliases: ["Uribou", "Inosasaou"], "img": "Uribou.gif" },
  { "name": "Hamham", aliases: ["Hamham", "Abraham"], "img": "Hamham.gif" },
  { "name": "Doyapon", aliases: ["Doyapon", "Doudanuki"], "img": "Doyapon.gif" },
  { "name": "Kyubi", "img": "Kyubi.gif" },
  { "name": "Nievacolas", "img": "Nievacolas.gif" },
  { "name": "Charlie", aliases: ["Charlie", "Ghostcycle"],  "img": "Charlie.gif" },
  { "name": "Kezurin", aliases: ["Kezurin", "Jinkotsukezuri"], "img": "Kezurin.gif" },
  { "name": "Hot Pot", aliases: ["Hot Pot", "Zundoumaru", "Shiryou no Dokudoku-nabe"], "img": "Hot_Pot.gif" },
  { "name": "Telespejo", "img": "Telespejo.gif" },
  { "name": "Jinta", aliases: ["Jinta", "Jingeki"], "img": "Jinta.gif" },
  { "name": "Kantaro", aliases: ["Kantaro", "Jihanki"], "img": "Kantaro.gif" },
  { "name": "Tidynator", aliases: ["Tidynator", "Robonyan 00"], "img": "Tidynator.gif" },
  { "name": "Kiborikkuma", aliases: ["Kiborikkuma", "Onikuma"], "img": "Kiborikkuma.gif" },
  { "name": "Junior", aliases: ["Junior", "Burning Dragon"], "img": "Junior.gif" },
  { "name": "Whisper", "img": "Whisper_2024.png" },
  { "name": "Sly", aliases: ["Sly", "Slimamander", "Super Sly", "Mitsumata Ghidorah"], "img": "Sly.gif" },
  { "name": "Becchan", aliases: ["Becchan", "Nuttarabeccha"], "img": "Becchan.gif" },
  { "name": "Dameboy", aliases: ["Dameboy", "Zettai Guardman"], "img": "Dameboy.gif" },
  { "name": "Fukurou", "img": "Fukurou.png" },
  { "name": "Intelecto", "img": "Intelecto.gif" },
  { "name": "Ogu Togu Mogu", aliases: ["Ogu Togu Mogu", "Ogu, Togu y Mogu", "Ogu, Togu & Mogu"], "img": "Ogu_Togu_Mogu.png" },
  { "name": "Voidera", "img": "Voidera.png" },
  { "name": "Shutendouji", aliases: ["Shutendouji", "Isotomas"], "img": "Shutendouji.png" },
  { "name": "Juno", "img": "Juno.png" },
  { "name": "Boreas", "img": "Boreas.png" },
  { "name": "Eurus", "img": "Eurus.png" },
  { "name": "Saros", "img": "Saros.png" },
  { "name": "Enma Demoniaco", aliases: ["Enma Demoniaco", "Yasha Enma", "Enma Iluminado", "Kakusei Enma"], "img": "Yasha_Enma.gif" },
  { "name": "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa.png" },
  { "name": "Kenshin Amaterasu", aliases: ["Kenshin Amaterasu", "Amaterasu"], "img": "Kenshin_Amaterasu.png" },
  { "name": "Suu-san", "img": "Suu-san.png" },
  { "name": "Nomi", aliases: ["Nomi", "Zashiki-warashi", "Tengu'ou Kurama"], "img": "Gnomey.gif" },
  { "name": "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa_LS.png" },
  { "name": "Kukuri-hime", "img": "Kukuri-hime.png" },
  { "name": "Gesshin Tsukuyomi", aliases: ["Gesshin Tsukuyomi", "Tsukuyomi"], "img": "Gesshin_Tsukuyomi.png" },
  { "name": "Gusto", aliases: ["Gusto", "Kaibyou Kamaitachi", "Neko'ou Bastet"], "img": "Gusto.gif" },
  { "name": "Kawauso", "img": "Kawauso.png" },
  { "name": "Tamamo", aliases: ["Tamamo", "Tamamo-no-mae"], "img": "Tamamo.gif" },
  { "name": "Gyuuki", "img": "Gyuuki.png" },
  { "name": "Narigama", "img": "Narigama.png" },
  { "name": "Blobgoblin", "img": "Blobgoblin.png" },
  { "name": "Azukiarai", "img": "Azukiarai.png" },
  { "name": "Kappa", aliases: ["Kappa", "Kappa'ou Sagojou"], "img": "Kappa.gif" },
  { "name": "Shien", "img": "Shien.png" },
  { "name": "Gran Enma Gouen", aliases: ["Gran Enma Gouen", "Gran Enma", "Enma Daiou"], "img": "Gran_Enma_Gouen.png" },
  { "name": "Naviwan", "img": "Naviwan.png" },
  { "name": "Konsaru", "img": "Konsaru.png" },
  { "name": "Dron", "img": "Dron.png" },
  { "name": "Alienigena", aliases: ["Alienigena", "Alien", "Miembro de la tribu Mikakunin"], "img": "Miembro_Mikakunin.png" },
  { "name": "Kitaro", "img": "Kitaro.png" },
  { "name": "Papa Ojo", aliases: ["Papa Ojo", "Medama Oyaji"], "img": "Papa_Ojo.png" },
  { "name": "Babamandra", "img": "Babamandra_SS.png" },
  { "name": "Medamanbou", aliases: ["Medamanbou", "Ojo de Babamandra"], "img": "Medamanbou.png" },    
  { "name": "Jingeki", "img": "Jingeki.png" },
  { "name": "Yamanbaa", aliases: ["Yamanbaa", "Yamambaa"], "img": "Yamanbaa_Boss.png" },
  { "name": "Shinmagunshin Fukurou", aliases: ["Shinmagunshin Fukurou", "Fukurou Corrupto"], "img": "Shinmagunshin_Fukurou.png" },
  { "name": "Lady Aracne", "img": "Lady_Aracne.png" },
  { "name": "Tamamo-no-mae", "img": "Tamamo-no-mae.png" },
  { "name": "Shinma Voidera", aliases: ["Shinma Voidera", "Shinma Douketsu", "Voidera Corrupto"], "img": "Voidera_Boss.png" },
  { "name": "Shien", "img": "Shien.png" },
  { "name": "Shinma Ananta", aliases: ["Shinma Ananta", "Shinma Kaira"], "img": "Ananta_Boss.png" },
  { "name": "Overseer", "img": "Overseer.png" },
  { "name": "Maten Overseer", aliases: ["Maten Overseer", "Maten Soranaki"], "img": "Maten_Overseer.png" },
  { "name": "Raidenryu", "img": "Raidenryu.png" },
  { "name": "Ananta Oscuro", aliases: ["Ananta Oscuro", "Yami Kaira"], "img": "Ananta_Oscuro.png" },
  { "name": "Acala Celestial", aliases: ["Acala Celestial", "Fudou Myouou Ten"], "img": "Acala_Celestial.png" },
  { "name": "Acala Exaltado", aliases: ["Acala Exaltado", "Acala Exalted"], "img": "Acala_Exaltado.png" },
  { "name": "Suzaku", "img": "Suzaku.png" },
  { "name": "Genbu", "img": "Genbu.png" },
  { "name": "Asura", "img": "Asura.png" },
  { "name": "Byakko", "img": "Byakko.png" },
  { "name": "Goemon", "img": "Goemon.png" },
  { "name": "Matsu", "img": "Matsu.png" },
  { "name": "Minamoto", "img": "Minamoto.png" },
  { "name": "Benkei", "img": "Benkei_P.png" },
  { "name": "Kyryn", "img": "Kyryn_C.png" },
  { "name": "Suzaku", "img": "Suzaku_C.png" },
  { "name": "Genbu", "img": "Genbu_C.png" },
  { "name": "Byakko", "img": "Byakko_C.png" },
  { "name": "Souryuu", "img": "Souryuu.png" },
  { "name": "Gunshin Susanoo", aliases: ["Gunshin Susanoo", "Susanoo"], "img": "Gunshin_Susanoo.png" }
];

let score = 0; 
let gameEnded = false; // Evita cambios una vez terminado el juego
const unlockedYoKai = new Set(); // Registro de Yo-kai desbloqueados por índice

// Normalizar la entrada del usuario (sin tildes y en minúsculas)
function normalizeString(str) {
    return str.normalize("NFD").replace(/[̀-\u036f]/g, "").toLowerCase();
}

// Crear el objeto de audio una sola vez
let getSound = new Audio("get.mp3");

// Reproducir sonido cuando se desbloquea un Yo-kai (sin solapamiento)
function playGetSound() {
    if (!getSound.paused) {
        getSound.pause(); // Detener el sonido actual si ya está reproduciéndose
        getSound.currentTime = 0; // Reiniciar el sonido al principio
    }
    getSound.play(); // Reproducir el sonido
}

// Actualizar la puntuación en formato (adivinados / totales)
function updateScoreDisplay() {
    const scoreDisplay = document.getElementById("score");
    scoreDisplay.textContent = `${score}/${yoKaiList.length}`;
}

// Verificar la respuesta del usuario
function checkAnswer() {
    if (gameEnded) return; // Si el juego ha terminado, no hacer nada

    const userAnswer = normalizeString(document.getElementById("answer-input").value.trim());

    let correctGuess = false; // Bandera para reproducir el sonido solo si hay aciertos

    yoKaiList.forEach((yoKai, index) => {
        // Normaliza todos los nombres asociados al Yo-kai
        const normalizedNames = [yoKai.name, ...(yoKai.aliases || [])].map(name => normalizeString(name));

        // Si la respuesta coincide con alguno de los nombres y no ha sido desbloqueado
        if (normalizedNames.includes(userAnswer) && !unlockedYoKai.has(index)) {
            const yoKaiImg = document.getElementById(`yo-kai${index + 1}`);
            if (yoKaiImg && yoKaiImg.src.includes("no-kai.png")) {
                yoKaiImg.src = yoKai.img; // Actualiza la imagen

                // Añadir clase para animación
                yoKaiImg.classList.add("yokai-unlocked");
                yoKaiImg.addEventListener("animationend", () => {
                    yoKaiImg.classList.remove("yokai-unlocked"); // Quitar clase tras animación
                });

                unlockedYoKai.add(index); // Marcar el Yo-kai como desbloqueado
                score++;
                correctGuess = true; // Se encontró un acierto
            }
        }
    });

    if (correctGuess) {
        playGetSound(); // Reproducir sonido solo si hubo un acierto
        updateScoreDisplay(); // Actualizar puntuación
        document.getElementById("answer-input").value = ""; // Borra la respuesta después de un acierto
    }

    checkGameEnd(); // Verifica si el juego ha terminado
}

// Verificar si el juego ha terminado (cuando se han adivinado todos los Yo-kai)
function checkGameEnd() {
    if (score === yoKaiList.length) {
        gameEnded = true;
        stopTimer(); // Detener el temporizador
        showCongratsImage(); // Mostrar imagen de "¡Felicidades!"
    }
}

// Mostrar la imagen de "¡Felicidades!" al finalizar el juego
function showCongratsImage() {
    const congratsImg = document.createElement("img");
    congratsImg.src = "congrats.gif";
    congratsImg.id = "congrats-image";
    congratsImg.style.position = "fixed";
    congratsImg.style.bottom = "0";
    congratsImg.style.left = "50%";
    congratsImg.style.transform = "translateX(-50%)";
    congratsImg.style.width = "100vw";
    congratsImg.style.zIndex = "1000";
    congratsImg.style.cursor = "pointer";

    // Ocultar la imagen al hacer clic
    congratsImg.addEventListener("click", () => {
        congratsImg.remove();
    });

    document.body.appendChild(congratsImg);
}

// Temporizador
let startTime;
let timerInterval;

function startTimer() {
    startTime = Date.now();
    timerInterval = setInterval(updateTimer, 1000);
}

function updateTimer() {
    const currentTime = Date.now();
    const elapsedTime = currentTime - startTime;

    const hours = Math.floor(elapsedTime / (1000 * 60 * 60));
    const minutes = Math.floor((elapsedTime % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((elapsedTime % (1000 * 60)) / 1000);

    const formattedTime = `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
    document.getElementById("time").textContent = formattedTime;
}

function stopTimer() {
    clearInterval(timerInterval);
}

// Manejador de evento: validación automática con "input"
document.getElementById("answer-input").addEventListener("input", checkAnswer);

// Inicializar el marcador y temporizador al cargar la página
updateScoreDisplay(); // Inicializa la puntuación en 0/total
startTimer();

window.addEventListener("beforeunload", (event) => {
    if (score > 0) { // Mostrar advertencia solo si hay progreso
        event.preventDefault();
        event.returnValue = "¿Estás seguro de que quieres salir? Se perderá todo el progreso.";
    }
});
